name: houses
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.2
  - conda-build
  # general packages
  - numpy=1.23.1
  - pandas=1.4.3
  - scikit-learn=1.1.2
  - category_encoders=2.5.0
  - kaggle=1.5.12
  - unzip=6.0
  - click=8.1.3
  # infrastructure
  - codecov
  - pytest=7.1.2
  - pre-commit=2.20.0
  - pylint=2.14.0
  # jupyter and visualization
  - ipykernel=6.15.1
  - plotnine=0.9.0
  - pip
  - pip:
    - mlflow==1.28.0
    - check-manifest==0.48
    - tox==3.25.1
    - setuptools==65.3.0
    - wheel==0.37.1

variables:
  AUTHOR: Nikola Shahpazov
  PURPOSE: Portfolio and personal learning
